### ISSUE TITLE
Feedback Valiu

### ISSUE THREAD

**Issue by S0c5** [daniloacc1991/screenshot_nodejs#1]
## Feedback

* Hey I saw that you only took screenshots from google when the test specified that it can be any URL, please refactor your code.
* Where are the unit tests?

https://github.com/daniloacc1991/screenshot_nodejs/blob/dce04b02fabefb0cd1d8918e3f0558a3ee95ff84/src/index.ts#L22

**Comment by daniloacc1991** [comment]
El código fue refactorizando y se implemento nestjs, adicional se implemento prueba unitaria
